[tool.poetry]
name = "sumorl"
version = "0.1.0"
description = "sumo+rl by ray"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
